# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180414_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_company_manager',
            field=models.BooleanField(default=False),
        ),
    ]
