# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_is_company_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='usernull', max_length=16),
        ),
    ]
