# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
